export const quotes = {
    "CAT": {
        "1": "A cat's purr is the sweetest melody. Keep them happy, and their hearts will sing",
        "2": "Cats are not just pets; they are family. Cherish every cuddle and every pounce",
        "3": "A happy cat is a healthy cat. Love them well, and they’ll love you back",
        "4": "Grooming isn’t just about looks; it’s a bond. Spend time brushing your cat and watch them shine",
        "5": "The secret to a happy cat? Plenty of playtime and a cozy spot to nap",
        "6": "Cats communicate through their eyes; let them know you care with gentle gazes and soft words",
        "7": "Create a safe haven for your cat, where curiosity meets comfort",
        "8": "Quality time with your cat is priceless. A simple game can strengthen your bond",
        "9": "Healthy food leads to a happy kitty. Invest in quality nutrition for your furry friend",
        "9": "Every cat deserves a warm lap and a sunny spot to lounge. Provide both!",
        "10": "Cats teach us to enjoy the little things—a sunbeam, a good stretch, or a quiet moment",
        "11": "Respect your cat’s space; they’ll come to you when they’re ready for affection",
        "12": "A well-exercised cat is a content cat. Engage their playful spirit with fun activities",
        "13": "A cat’s love is unconditional. Return that love with kindness and patience",
        "14": "Be the cat parent your feline dreams of—loving, attentive, and playful!",
        "15": "Cats are masters of relaxation. Follow their lead and take time to unwind together",
        "16": "The right toys can spark joy in your cat’s life. Choose wisely and watch them thrive",
        "17": "Regular vet check-ups keep your cat healthy and happy. Don’t skip them!",
        "18": "Cats thrive in routine. Keep their feeding and playtime consistent for peace of mind",
        "19": "Every purr tells a story of love. Listen closely and respond with affection",
    },
    "DOG": {
        "1": "A happy dog is a wagging tail. Love them, and they’ll love you forever",
        "2": "Dogs are family, not just pets. Treat them with the care they deserve",
        "3": "A daily walk is more than exercise—it’s quality bonding time with your dog",
        "4": "Healthy food, happy dog. Nourish them well for a lifetime of tail wags",
        "5": "Every dog needs love, exercise, and a comfy spot to rest. Provide all three!",
        "6": "Grooming keeps your dog looking good and feeling great. Make it a fun routine",
        "7": "Dogs communicate with their eyes and tail—pay attention, and you’ll know what they need",
        "8": "Training builds trust. Teach with kindness, and your dog will always listen",
        "9": "A dog's love is pure and loyal. Give them your time, and they’ll give you their heart",
        "10": "Exercise is the key to a happy dog. Play fetch, go for walks, and enjoy the outdoors together",
        "11": "A well-fed dog is a happy dog. Choose healthy, nutritious meals for your furry friend",
        "12": "The joy of a dog is in the small things—a belly rub, a treat, or just your presence",
        "13": "Dogs thrive on routine. Keep their days structured for a calm and balanced pup",
        "14": "Training isn’t just for obedience; it’s for bonding. Spend time teaching, and you'll grow closer",
        "15": "Dogs need mental stimulation too. Keep their minds sharp with fun challenges and toys",
        "16": "Your dog looks up to you—literally and figuratively. Be the leader they deserve",
        "17": "A tired dog is a happy dog. Make sure they get plenty of exercise every day",
        "18": "Dogs need a place to feel safe. Give them a cozy corner of the house to call their own",
        "19": "Vet visits are essential for your dog’s health. Keep them up to date on care and vaccinations",
        "20": "Love your dog like family, because to them, you are their whole world",
    },
    "DUCK": {
        "1": "A happy duck is a well-fed duck. Provide fresh food and clean water daily",
        "2": "Ducks love to swim! Make sure they have access to a clean pond or pool",
        "3": "A cozy, dry shelter keeps your ducks safe from the elements and predators",
        "4": "Ducks need companionship. Keep them in pairs or groups for their well-being",
        "5": "Healthy ducks need space to roam. Give them plenty of room to explore",
        "6": "Fresh greens make a great treat for ducks. Add variety to their diet with veggies",
        "7": "Ducks are curious by nature—give them toys or new areas to discover!",
        "8": "Protect your ducks from predators with secure fencing and covered areas",
        "9": "Ducks love routine. Keep their feeding and care schedule consistent",
        "10": "Provide grit to your ducks to help with digestion and keep them healthy",
        "11": "Clean, fresh water is essential for ducks to stay hydrated and clean",
        "12": "Ducks are social creatures—interact with them regularly for happy, friendly pets",
        "13": "Make sure your ducks have dry bedding to prevent health issues and discomfort",
        "14": "A balanced diet keeps your ducks healthy. Provide a mix of grains, greens, and waterfowl feed",
        "15": "Ducks enjoy a splash in clean water—it keeps them happy and their feathers in top shape",
        "16": "Provide shade and shelter for your ducks during hot weather to prevent overheating",
        "17": "Ducks love foraging. Let them roam and search for insects, seeds, and grasses",
        "18": "Regular health checks can help catch any issues early. Keep an eye on your ducks’ behavior",
        "19": "Egg-laying ducks need extra calcium. Make sure to supplement their diet with crushed shells or other sources",
        "20": "Ducks thrive in natural environments. Create a habitat that mimics their wild surroundings",
    },
    "DOVE": {
        "1": "Doves are symbols of peace; nurture them with love and gentle care",
        "2": "A clean cage is essential for happy doves. Keep their home tidy and fresh",
        "3": "Doves thrive on companionship. Keep them in pairs or small groups for happiness",
        "4": "Feed your doves a balanced diet of seeds, grains, and fresh greens for optimal health",
        "5": "Regular social interaction helps build trust with your doves. Spend time with them daily",
        "6": "Doves enjoy safe space to fly. Provide ample room for them to stretch their wings",
        "7": "Fresh water is crucial. Change it daily to keep your doves hydrated and healthy",
        "8": "Doves love to bathe! Offer a shallow dish of water for them to enjoy",
        "9": "Provide perches of various sizes and textures for your doves to explore and exercise",
        "10": "Doves are sensitive creatures. Keep their environment calm and quiet for peace of mind",
        "11": "Routine matters to doves. Maintain a consistent feeding and care schedule",
        "12": "A varied diet keeps doves engaged and happy. Introduce new foods regularly",
        "13": "Doves communicate with coos; listen closely to understand their needs and feelings",
        "14": "Encourage nesting behavior by providing suitable materials for your doves",
        "15": "Monitor your doves for any signs of illness. Early detection is key to their health",
        "16": "Doves appreciate toys and mirrors to stimulate their curiosity and playfulness",
        "17": "Keep your doves in a well-ventilated area to prevent respiratory issues",
        "18": "Doves are gentle souls. Approach them slowly and calmly to build trust",
        "19": "Create a cozy environment with nesting boxes to make your doves feel safe and secure",
        "20": "Celebrate their unique personalities; every dove brings joy in its own special way",
    }
}